#!/usr/bin/env bash
#
# Publishes a release to Smithery.
#
# Credentials come from the environment only — never hardcode a key in this file.
#   export SMITHERY_API_KEY=...            (local)
#   SMITHERY_API_KEY: ${{ secrets.SMITHERY_API_KEY }}   (CI)
#
# The payload is generated by scripts/smithery-payload.mjs from the live server's
# tools/list response, so the published tool list cannot drift from the code.
#
# Usage:
#   npm run build && npm run bundle && bash scripts/smithery-publish.sh
#   bash scripts/smithery-publish.sh --dry-run     # build + validate, publish nothing
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

QUALIFIED_NAME="masv%2Fmasv"
BUNDLE="masv-mcp-server.mcpb"

# Explicit XXXXXX template: portable across BSD (macOS) and GNU (CI) mktemp.
# `mktemp -t prefix` works on macOS but GNU coreutils rejects a template with no X's.
TMP_DIR="${TMPDIR:-/tmp}"; TMP_DIR="${TMP_DIR%/}"
PAYLOAD_FILE="$(mktemp "${TMP_DIR}/smithery-payload.XXXXXX")"
trap 'rm -f "$PAYLOAD_FILE"' EXIT

# --- credential -------------------------------------------------------------
# ':?' aborts with a clear message rather than sending an empty bearer token.
if [ "$DRY_RUN" -eq 0 ]; then
  : "${SMITHERY_API_KEY:?SMITHERY_API_KEY is not set. Export it, or pass --dry-run.}"
fi

# --- bundle -----------------------------------------------------------------
# Deliberately does NOT build. Publishing is a release action, so the artifact
# must already exist and have been built as an explicit, reviewable step.
if [ ! -f "$BUNDLE" ]; then
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "==> WARNING: $BUNDLE not found (dry run continues; payload only)"
  else
    {
      echo "ERROR: $BUNDLE not found."
      echo "       Run 'npm run bundle' first. This script will not build it for you,"
      echo "       so publishing is always a deliberate step."
    } >&2
    exit 1
  fi
elif [ -z "${GITHUB_ACTIONS:-}" ] &&
     [ -n "$(find build -type f -newer "$BUNDLE" -print -quit 2>/dev/null)" ]; then
  # A bundle older than the compiled output means someone changed code and
  # forgot to repack — exactly the stale-release mistake worth blocking.
  #
  # Local-only by design. In CI this heuristic cannot produce a true positive: the
  # bundle is an immutable artifact of this same workflow run, downloaded by artifact
  # ID, so it cannot be a leftover from an earlier run. The release job then has to
  # run `npm ci && npm run build` — scripts/smithery-payload.mjs spawns the built
  # server to read tools/list — which leaves build/ newer than the downloaded file and
  # would trip this every time. Every CI trigger would be a false positive.
  #
  # The existence check above still applies everywhere.
  {
    echo "ERROR: $BUNDLE is older than files in build/ — it is stale."
    echo "       Rebuild it:  npm run bundle"
  } >&2
  exit 1
fi

# --- payload ----------------------------------------------------------------
echo "==> Generating payload from live server tools/list"
node scripts/smithery-payload.mjs > "$PAYLOAD_FILE"

VERSION=$(node -p "require('./package.json').version")
if [ -f "$BUNDLE" ]; then
  echo "    version=$VERSION  bundle=$BUNDLE ($(du -h "$BUNDLE" | awk '{print $1}'))"
else
  echo "    version=$VERSION  bundle=(missing)"
fi

if [ "$DRY_RUN" -eq 1 ]; then
  echo "==> Dry run — not publishing. Payload written to:"
  echo "    $PAYLOAD_FILE"
  trap - EXIT
  exit 0
fi

# --- publish ----------------------------------------------------------------
echo "==> Publishing to Smithery"
STATUS=$(curl -sS -X PUT \
  "https://api.smithery.ai/servers/${QUALIFIED_NAME}/releases" \
  -H "Authorization: Bearer ${SMITHERY_API_KEY}" \
  -F "payload=<${PAYLOAD_FILE}" \
  -F "bundle=@./${BUNDLE}" \
  -o /tmp/smithery-response.json \
  -w "%{http_code}")

echo "    HTTP $STATUS"
if [ "$STATUS" -lt 200 ] || [ "$STATUS" -ge 300 ]; then
  echo "ERROR: publish failed" >&2
  cat /tmp/smithery-response.json >&2 || true
  exit 1
fi

echo "OK  published $VERSION to Smithery"
